### ISSUE TITLE
TODO: Readme and Docs expansion

### ISSUE THREAD

**Issue by donuts-are-good** [donuts-are-good/bearclaw#14]
Plugins were pretty quick to be implemented, but as other issues have highlighted, the explanation around a lot of this stuff is a bit thin. The plugin directory is somewhat secondary, however an explanation of what the heck a plugin would be for and an explanation of how to use them is imperative. 

It'd probably be a good idea to make the Readme more 'modular' and have a table of contents with links to explainers of various concepts, features etc, while keeping the main operating instructions for bearclaw in the bearclaw Readme body itself. Perhaps this a good use of the wiki feature, if there are those who prefer wikis to longer-format Readmes.

**Comment by hollisticated-horse** [comment]
I think keeping to simple links and markdown files in the repo is safer, if there is a need to migrate from Github. 
Happy to help out though to write the workings of bearclaw.

**Comment by donuts-are-good** [comment]
That's a good point. I'm going to take a look at the way the code in the folder is structured, and let's see if we can streamline things with a bearclaw/docs folder that contains markdown documents that are linked to from the Readme in the Table of Contents, or a brief list of topics to choose from. That way when clicked, it remains portable.

**Comment by donuts-are-good** [comment]
documentation in general needs an overhaul. had an idea while im working on `posts.html` and `index.html`  -  bearclaw should ship with its own documentation inside of `bearclaw/markdown`, not only so that it ships with good documentation, but so that the main website can be served as a copy of that documentation. 

this will also obviate the need for the CPX11, as the site can be hosted from the docs directory. 

just an idea. it should ship with its documentation in the markdown folder though. that way it's like a toy with the batteries that come with it so you can play with it on the ride home.

**Comment by donuts-are-good** [comment]
changing the title to reflect the objective accurately. picking up this ticket next.

**Comment by hollisticated-horse** [comment]
What about having a good write up viewable with `--help` or `-h` in the binary itself ?

**Comment by donuts-are-good** [comment]
the binary should already output the descriptions for the options if you do --help or -? currently i -think-...

yep

![image](https://user-images.githubusercontent.com/96031819/222917851-7a218da1-e9d7-4742-b8bf-5550ded88f33.png)

**Comment by donuts-are-good** [comment]
just a heads up, it's `-h` and `--help`, however `--?` doesn't do anything.

**Comment by donuts-are-good** [comment]
also, it's not me, per se that creates this menu, it's a feature of the language. i just define the flag and the message. i can make a custom one, but the peril there becomes added functionality not being added to the list by hand whereas now if i have a flag at all, it will be in that list.

**Comment by hollisticated-horse** [comment]
Seems perfectly readable to me :grin: the flag method seems perfect as is.

**Comment by hollisticated-horse** [comment]
List of things to document: 
- project overview
- project init
- project structure
- opinionated features
- markdown supported elements ? 

Should all of this be in a single file or multiple files ? And how does it link to the project README.md ?

**Comment by donuts-are-good** [comment]
So, in the past when I've had a project with a huge README.md, what we do is put the most pertinent surface level things on the front page: name of the program, what it does, some branding, then a summary of links like a table of contents. 

The idea I like the most is for us to have the README.md on github reference the markdown documents that we'll ship in the markdown folder. The markdown documents we ship in the markdown folder will give users something to test the program with real fast when they download it, and it will also generate the code for bearclaw.blog (i set up a bearclaw instance for the bearclaw URL and routed it)

This way, if you're on github, and you're clicking around the readme, it will send you to the markdown content and render it for you on github, and if you download a copy of bearclaw, it will be in the markdown folder ready for you to run bearclaw and generate the html which you can read in a browser. I think it's pretty clever that we have essentially two forms of documentation, our website, and a demo included all from one set of docs.

**Comment by donuts-are-good** [comment]
> List of things to document:
> 
>     * project overview
> 
>     * project init
> 
>     * project structure
> 
>     * opinionated features
> 
>     * plugins
> 
>     * markdown supported elements ?
> 
> 
> Should all of this be in a single file or multiple files ? And how does it link to the project README.md ?

This is a good start. Should we do FAQ style or keep it light? There's something that hasn't made it into the documentation yet that I do spend quite a bit of time thinking about. I'd like to come up with a concise way to define the things that led to bearclaw getting made, like the need for simplicity. Sometimes for me it can be tempting to handle every edge case, and add every complexity, but I always return to asking myself "does this code im adding make things simpler". 

If that could be distilled into a simple simple mission statement, at least from the engineering side, that'd be helpful for future code contributors who might just arrive and think "all static generators need a templating language" and PR the addition of Jade or something. 

There are a few core concerns I like to have in mind when building: simplicity, easy words, generality rather than specificity with regard to the moving parts, commenting every line, sticking to stdlib when at all possible, less is more, user agency, portability, descriptive variables, etc.

Most of my concerns tend to center around engineering decisions. I wish I had more time to dedicate to the visual side of things.

**Comment by donuts-are-good** [comment]
picking up ticket.

**Comment by hollisticated-horse** [comment]
I'm pretty busy this week, but I've had a quick read and will try to make a draft by the end of the week :D 

I quite like that 
1. the documentation is linked in the README.md with A TOC,
2. it can be a FAQ or have one, and 
3. it can than be used as demo posts for new users and 
4. be seen as posts in bearclaw.blog

Having that + tool flags is simple and illustrative in a good way.

**Comment by donuts-are-good** [comment]
https://github.com/donuts-are-good/bearclaw/commit/f4da31c4b289375d2e0c790a3df960f1afc03b85

**Comment by donuts-are-good** [comment]
> I'm pretty busy this week, but I've had a quick read and will try to make a draft by the end of the week :D
> 
> I quite like that
> 
>     1. the documentation is linked in the README.md with A TOC,
> 
>     2. it can be a FAQ or have one, and
> 
>     3. it can than be used as demo posts for new users and
> 
>     4. be seen as posts in bearclaw.blog
> 
> 
> Having that + tool flags is simple and illustrative in a good way.

woops i just saw this, i went ahead and typed up docs today

**Comment by donuts-are-good** [comment]
https://github.com/donuts-are-good/bearclaw/commit/cff01d134b30c1e23a8d43f82d26d55367f6f2f7
