### ISSUE TITLE
 split module and tool 

### ISSUE THREAD

**Issue by ghost** [donuts-are-good/bearclaw#31]
currently the module is not importable, since its just the tool

**Comment by donuts-are-good** [comment]
Tell me about how you're wanting to use it, maybe I can help out

**Comment by 1268** [comment]
I would just like the freedom to be able to import the module and make my own tool if I want to make any tweaks. currently I am using:

https://github.com/piranha/gostatic

but I like the small size of BearClaw

**Comment by donuts-are-good** [comment]
If it were a module, what methods would you expect to use from it? I'm trying to size it up in my head before I make any promises

**Comment by 1268** [comment]
usually the process for something like this involves replacing all references at the module level to `os` package with something like `io.Reader` or `io.Writer`, then using `os` as needed at the tool level. then people can use whatever reader or writer works for their use case.
