### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by gaffo** [donuts-are-good/bearclaw#4]
It'd be great to have some install instructions... or downloadable builds.

**Comment by donuts-are-good** [comment]
Thank you for checking out bearclaw and filing the issues, I appreciate your time. This is a great idea, I will do this!

**Comment by donuts-are-good** [comment]
In progress! https://github.com/donuts-are-good/bearclaw/pull/15

**Comment by donuts-are-good** [comment]
It looks like we have two issues on this one, condensing the two issues into one.

https://github.com/donuts-are-good/bearclaw/issues/6
