### ISSUE TITLE
BUG REPORT - Not go installable

### ISSUE THREAD

**Issue by gaffo** [donuts-are-good/bearclaw#5]
**What happened?**

I tried to go install

**What should have happened?**

it should have installed

**More information:**
go version go1.19.4 darwin/arm64

go install github.com/donuts-are-good/bearclaw@latest
go: downloading github.com/donuts-are-good/bearclaw v0.0.0-20230226015146-7af32f3755ea
go: github.com/donuts-are-good/bearclaw@latest: github.com/donuts-are-good/bearclaw@v0.0.0-20230226015146-7af32f3755ea: parsing go.mod:
	module declares its path as: bearclaw
	        but was required as: github.com/donuts-are-good/bearclaw

**Comment by diamondburned** [comment]
This works now:

```
―❤―▶ go install github.com/donuts-are-good/bearclaw@latest

―❤―▶ bearclaw -h
Usage of bearclaw:
  -watch
    	watch the current directory for changes
```

I also took the liberty of renewing the Go modules proxy cache to have this commit :)

**Comment by gaffo** [comment]
this works!
