### ISSUE TITLE
Feature:  detect modification of preexisting blog posts, in the markdown folder. 

### ISSUE THREAD

**Issue by hollisticated-horse** [donuts-are-good/bearclaw#8]
**describe the feature**
Current behavior is to detect new files in markdown folder to then generate blog. 
would it be possible to have bearclaw detect file modification as well.

**Comment by donuts-are-good** [comment]
Thanks for the issue. Cool idea, and actually something that's been rolling around lately on this end too. Is this with or without --watch enabled?

**Comment by hollisticated-horse** [comment]
This would probably be best for `--watch`.
Maybe also force `--output` flag, to be sure to regenerate in the right place ?

**Comment by donuts-are-good** [comment]
> This would probably be best for --watch.

This is doable

> Maybe also force --output flag, to be sure to regenerate in the right place ?

an --output flag would be nice, but forcing it to be used maybe not so much. the program should be able to run on its own when executed without arguments using sane defaults, to keep with the simplicity.

> And maybe a how to set it to run as daemon / in the background (very hypothetical, don't know if that's implementable...).

I agree. This is what the Systemd instructions are showing in the Readme. What init system do you use? I can include alternate instructions for other systems.

**Comment by donuts-are-good** [comment]
An interesting but with this today was reported by @stanleylw - will be appending to this issue when I receive more clarity on what --watch behavior is breaking on his end

**Comment by donuts-are-good** [comment]
This should now be fixed. Please reopen if the current master branch does not contain the necessary fixes.
