### ISSUE TITLE
BUG REPORT - index.html not generated

### ISSUE THREAD

**Issue by hollisticated-horse** [donuts-are-good/bearclaw#9]
**describe the feature**
There is no index.html generated. 
Bearclaw could generate the index.html based on a specific now.md page, that serves as a now page and homepage:

https://nownownow.com/about
https://maggieappleton.com/now

**Comment by donuts-are-good** [comment]
In the current stable build, there was a bug where it didn't generate an index.html and I think was doing main.html instead. Have you tested to see if index.html is generated in the alpha? The alpha build should generate an about.html where the credits are auto inserted for the plugins being used, which could be used (via plugin conveniently as well) to add "now" content if desired. However I can't remember if about.html only gets generated when a plugin is used or not. I can check on it this weekend but if you want to fire up the alpha and annotate this issue you can.

**Comment by gaffo** [comment]
I just did @latest as of about 10 minutes ago... I only get an empty about.html, feed.xml, posts.html

**Comment by donuts-are-good** [comment]
Thank you, will investigate this week during work breaks or this weekend. You've been a big help getting these issues sorted, and I sure appreciate your input!

**Comment by hollisticated-horse** [comment]
> In the current stable build, there was a bug where it didn't generate an index.html and I think was doing main.html instead. Have you tested to see if index.html is generated in the alpha? The alpha build should generate an about.html where the credits are auto inserted for the plugins being used, which could be used (via plugin conveniently as well) to add "now" content if desired. However I can't remember if about.html only gets generated when a plugin is used or not. I can check on it this weekend but if you want to fire up the alpha and annotate this issue you can.

@donuts-are-good 

The now.html or index.html as now page doesn't have to be hard coded. **I just thought that it would be neat to have an index.html generate as part of the base pre-generated structure.** 

I'm clearly using mine as a now page, but it can be anything I guess.

**Comment by donuts-are-good** [comment]
> I just thought that it would be neat to have an index.html generate as part of the base pre-generated structure.

Absolutely. I will do this. We are both on the same page 100% :)

**Comment by donuts-are-good** [comment]
so, as im sitting here coding on this and trying to visualize what 'copy text' would go on the `index.html` I'm realizing that `posts.html` behaves the way an `index.html` would behave in a simple tiny blog site. I think a great way to maintain simplicity is to combine the two, and change `posts.html` into index.html

**Comment by donuts-are-good** [comment]
also posts.html should specify that there's a list of all posts otherwise it just looks empty.

**Comment by donuts-are-good** [comment]
> so, as im sitting here coding on this and trying to visualize what 'copy text' would go on the `index.html` I'm realizing that `posts.html` behaves the way an `index.html` would behave in a simple tiny blog site. I think a great way to maintain simplicity is to combine the two, and change `posts.html` into index.html

trying this on for size. can be reverted later if it is ugly.

**Comment by donuts-are-good** [comment]
This is fixed in https://github.com/donuts-are-good/bearclaw/commit/583423522bf4803fec05286135d1a66cf6a51262
